### ISSUE TITLE
Is FirebaseLink Mac only ?

### ISSUE THREAD

**Issue by ndroock1** [keshavsaharia/FirebaseLink#3]
Considering the use of "!command" I doubt that this was ever tested on Windows.

**Comment by keshavsaharia** [comment]
Thank you for adding Windows compatibility. I would be happy to make you a collaborator on this repository or link to your fork if you are interested in maintaining it.

**Comment by zaom01** [comment]
this file work only with windows ? because i need it to work on linux system
