### ISSUE TITLE
Please update CurlRequest function.

### ISSUE THREAD

**Issue by ndroock1** [keshavsaharia/FirebaseLink#4]
With this code the package also works on Windows.

CurlRequest[verb_,data_,url_]:=
If[$OperatingSystem == "Windows",
If[$FirebaseUseBuffer,
    Export[$FirebaseCurlBuffer,data,"JSON"];
    Run["curl -X "<>verb<>" -H 'Content-type:application/json' --data @"<>$FirebaseCurlBuffer<>" "<>url<>" ","JSON"],
    Run["curl -X "<>verb<>" -H 'Content-type:application/json' -d '"<>CurlEscape[data]<>"' "<>url<>" ","JSON"]
],
If[$FirebaseUseBuffer,
	Export[$FirebaseCurlBuffer, data, "JSON"];
	Import["!curl -X "<>verb<>" -H 'Content-type:application/json' --data @"<> $FirebaseCurlBuffer <> " '"<> url <>"'", "JSON"],
	Import["!curl -X "<>verb<>" -H 'Content-type:application/json' -d '"<> CurlEscape[data] <> "' '"<> url <>"'", "JSON"]
];
]

**Comment by keshavsaharia** [comment]
Thank you for opening the issue, I forgot to reference it in the commit but it has been updated.

**Comment by zaom01** [comment]
Hello ,

**Comment by zaom01** [comment]
This file work only with Windows ?
