### ISSUE TITLE
FirebaseChild error on unauthenticated database

### ISSUE THREAD

**Issue by bloorr** [keshavsaharia/FirebaseLink#5]
FirebaseRead[fb, FirebaseChild[fb,"text"]]
generates
{"error" -> "Could not parse auth token."}

Discovered problem while working through Google tutorial.

Fixed with:
FirebaseChild[firebase_, child_] := If[Length[firebase] > 1, 
										Firebase[FileNameJoin[{First[firebase], child}],Last[firebase]],
										Firebase[FileNameJoin[{First[firebase], child}]]]

**Comment by keshavsaharia** [comment]
Thanks for opening this issue! I just updated the master with these changes.
